### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Shamanou**
Added a lot of documentation on how to push to an FDP. I also fixed a minor bug wich prevented the new metadata editor form loading.

### CODE REVIEW

**Comment by kburger** [comment]
It looks like this pull request cannot be automatically incorporated at this point because of a conflict in the metadata-form submodule. I assume this can be resolved by updating the submodule to the latest commit and pushing those changes.

**Review by kburger — COMMENTED** [review]
Is it possible to put style changes like the frame width (https://github.com/DTL-FAIRData/FAIRifier/pull/1/commits/a0ca2ebd2d5a88221be762a5fc31700a58c497e7) in a css file? Might make it easier to maintain in the long run.

**Comment by Shamanou** [comment]
Yes thats possible

Op wo 19 apr. 2017 10:36 schreef kburger <notifications@github.com>:

**Review by kburger — COMMENTED** [review]
The building section in https://github.com/DTL-FAIRData/FAIRifier/pull/1/commits/293c374a28a8c2bfc8c292e37fd679537a50d3a9 can be updated by removing the npm installation, and the npm gulp and bower installation commands. The metadata-form repository now provides minified dist files, so building the files locally is no longer necessary.

**Review by kburger — COMMENTED** [review]
Minor typos on https://github.com/DTL-FAIRData/FAIRifier/pull/1/commits/293c374a28a8c2bfc8c292e37fd679537a50d3a9: 'tripple' should be 'triple'

**Review by kburger — COMMENTED** [review]
I am not yet familiar with the build setup for refine: is it necessary to include the libraries in the repository as well, or could they be resolved during the build process, locally? I know this conflicts with my previous comment on removing the bower install step from the readme.

**Comment by Shamanou** [comment]
Yes thats nescasaary unless we move to maven

Op wo 19 apr. 2017 10:46 schreef kburger <notifications@github.com>:

**Comment by kburger** [comment]
Forgot to include the specific commit in my last comment: https://github.com/DTL-FAIRData/FAIRifier/pull/1/commits/22c4d6b8eaadf696275a2ef1140299168132aa2a. I was referring to the front-end dependencies.

**Pull request merged**
